DROP DATABASE IF EXISTS consigueVentas;
CREATE DATABASE consigueVentas;
USE consigueVentas;

CREATE TABLE ROLES(
  ID_RO     	 TINYINT          AUTO_INCREMENT, 
  DESCRIPCION    VARCHAR(20)      NOT NULL UNIQUE,
  PRIMARY KEY (ID_RO)
);

INSERT INTO ROLES (DESCRIPCION) VALUES('ADMINISTRADOR');
INSERT INTO ROLES (DESCRIPCION) VALUES('CLIENTE');

CREATE TABLE ESTADOS(
  ID_ES     	 TINYINT          AUTO_INCREMENT, 
  DESCRIPCION    VARCHAR(20)      NOT NULL UNIQUE,
  PRIMARY KEY (ID_ES)
  );
  
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('ACTIVO');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('INACTIVO');

CREATE TABLE DISTRITOS
(
    ID_DI  	   TINYINT AUTO_INCREMENT,
    NOMBRE     	   VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DI)
);

INSERT INTO DISTRITOS (NOMBRE) VALUES ('LIMA');
INSERT INTO DISTRITOS (NOMBRE) VALUES ('ANCON');
INSERT INTO DISTRITOS (NOMBRE) VALUES ('ATE');
INSERT INTO DISTRITOS (NOMBRE) VALUES ('BARRANCO');
INSERT INTO DISTRITOS (NOMBRE) VALUES ('BREÑA');
INSERT INTO DISTRITOS (NOMBRE) VALUES ('CARABAYLLO');
INSERT INTO DISTRITOS (NOMBRE) VALUES ('CHACLACAYO');

CREATE TABLE USUARIOS(
  ID_US      	INT         		AUTO_INCREMENT, 
  DNI   	CHAR(8)      	 	NOT NULL,
  NOMBRE    	VARCHAR(50)  		NOT NULL,
  APELLIDO    	VARCHAR(50)		NOT NULL,
  TELEFONO  	CHAR(9)  		NOT NULL,
  DIRECCION	VARCHAR(150) 		NULL,
  CORREO 	VARCHAR(50)	 	NOT NULL,
  CLAVE  	VARCHAR(50)  	 	NOT NULL,
  ID_RO	 	TINYINT	 		NOT NULL DEFAULT 2,
  ID_ES  	TINYINT    		NOT NULL DEFAULT 1,
  ID_DI		TINYINT			NOT NULL,
  PRIMARY KEY (ID_US),
  FOREIGN KEY (ID_RO) REFERENCES ROLES 	 (ID_RO),
  FOREIGN KEY (ID_ES) REFERENCES ESTADOS (ID_ES),
  FOREIGN KEY (ID_DI) REFERENCES DISTRITOS (ID_DI)
);

INSERT INTO USUARIOS (DNI,NOMBRE,APELLIDO,TELEFONO,DIRECCION,CORREO,CLAVE,ID_RO,ID_DI)
VALUES ('72747310','DARLY JACK','GÓNGORA CHINGAY','917417298','RICARDO FEIJOO 235','djackgongora@gmail.com','admingongora',1,1);

/*PROCEDURE PARA INSERTAR USUARIOS*/

DELIMITER $$
CREATE PROCEDURE sp_InsUsuarios
(
DNI 		CHAR(8),
NOMBRE 		VARCHAR(50),
APELLIDO 	VARCHAR(50),
TELEFONO 	CHAR(9),
DIRECCION 	VARCHAR(150),
CORREO 		VARCHAR(50),
CLAVE  		VARCHAR(50),
DISTRITO 	TINYINT
)
	BEGIN
INSERT INTO USUARIOS (DNI,NOMBRE,APELLIDO,TELEFONO,DIRECCION,CORREO,CLAVE,ID_DI) VALUES (DNI,NOMBRE,APELLIDO,TELEFONO,DIRECCION,CORREO,CLAVE,DISTRITO);
	END$$
DELIMITER ;

CALL sp_InsUsuarios('99999999','DIEGO','ANDRES','999999999','LOS PALETAS 555','diegogc@gmail.com','clientegutarra',4);

/*PROCEDURE PARA ACTUALIZAR USUARIOS*/

DELIMITER $$
CREATE PROCEDURE sp_UpdUsuarios
(
DNI 		CHAR(8),
NOMBRE 		VARCHAR(50),
APELLIDO 	VARCHAR(50),
TELEFONO 	CHAR(9),
DIRECCION 	VARCHAR(150),
CORREO 		VARCHAR(50),
CLAVE  		VARCHAR(50),
DISTRITO 	TINYINT,
CODIGO 		INT
)
	BEGIN
UPDATE USUARIOS SET DNI=DNI, NOMBRE=NOMBRE, APELLIDO=APELLIDO, TELEFONO=TELEFONO, DIRECCION=DIRECCION, CORREO=CORREO, CLAVE=CLAVE, ID_DI=DISTRITO WHERE ID_US=CODIGO;
	END$$
DELIMITER ;

CALL sp_UpdUsuarios('74455126','MIGUEL','TAFURA PELAEZ','955141415','AV.MIRAFLORES 555','mitape555@gmail.com','12345',4,2);

/*PROCEDURE PARA LISTAR LOS USUARIOS CON ESTADO ACTIVO*/

DELIMITER $$
CREATE PROCEDURE sp_SelUsuarios()
	BEGIN
SELECT U.ID_US, U.DNI, U.NOMBRE, U.APELLIDO, U.TELEFONO, U.DIRECCION, U.CORREO, U.CLAVE, R.DESCRIPCION , D.NOMBRE AS 'DISTRITO' FROM USUARIOS AS U
INNER JOIN ROLES AS R
ON R.ID_RO = U.ID_RO
INNER JOIN DISTRITOS AS D
ON D.ID_DI = U.ID_DI
WHERE U.ID_ES=1;
	END$$
DELIMITER ;

CALL sp_SelUsuarios();

/*PROCEDURE PARA ELIMINAR USUARIOS*/

DELIMITER $$
CREATE PROCEDURE sp_DroUsuarios
(
CODIGO INT
)
	BEGIN
UPDATE USUARIOS SET ID_ES=2 WHERE ID_US=CODIGO;
	END$$
DELIMITER ;

CALL sp_DroUsuarios (2);


